### ISSUE TITLE
bcrypt dependency out of date and fails install in NodeJs14

### ISSUE THREAD

**Issue by andybriggs** [venables/bookshelf-secure-password#19]
Running `npm i` using NodeJs14 fails due to out of date bcrypt dependency.

Changing bcrypt version to 5.0.0 resolves the issue and appears to function as expected within my project however I've not tested extensively.  It would be great to get this dependency bumped if possible!

**Comment by andybriggs** [comment]
It also seems to fail install using Node 13

**Comment by andreacanton** [comment]
Here some more info about the severity of this issue https://app.snyk.io/vuln/SNYK-JS-BCRYPT-572911

**Comment by andreacanton** [comment]
I made a PR #20

**Comment by venables** [comment]
Closing now that #20 has been merged.  Thank you for the help!

**Comment by andreacanton** [comment]
> Closing now that #20 has been merged. Thank you for the help!

when could you put in a new patch release? Thank you.
