### ISSUE TITLE
model.authenticate throws a password mismatch error despite the passwords matching

### ISSUE THREAD

**Issue by jmeyers91** [venables/bookshelf-secure-password#6]
I'm trying to use this plugin, but it's throwing `PasswordMismatchError` errors when I try to use it with test data.

Here is my login code. I'm testing with `username = "admin@test.com"`, `password = "password"`, and `usernameField = "email"`. And I've confirmed (with `console.log`) that these values are correct and that a user is being resolved by `fetch`.

```
return Model.forge({ [usernameField]: username })
  .fetch()
  .then((user) => {
    console.log({user, username, password, usernameField});
    if(!user) return null;
    return user.authenticate(password);
  })
  .catch((error) => {
    console.log('login error', error);
    return null;
  });
```

Here is my seed file that creates the user with the credentials above:

```
exports.seed = async (knex) => {
  const AdminUser = require('../lib/models/AdminUser');

  await knex('admin_users').del();
  await AdminUser.forge({
    first_name: 'admin',
    last_name: 'admin',
    email: 'admin@test.com',
    password: 'password',
  }).save();
};
```

And here is the model definition for `AdminUser`:

```
const AdminUser = app.model('AdminUser', {
  tableName: 'admin_users',
  hasSecurePassword: true,
  hasTimestamps: ['createdAt', 'updatedAt'],
});
```

**Comment by venables** [comment]
Hi @jmeyers91 -- sorry you're having issues with the plugin.  It looks like you might be using it in conjunction with some other plugin (what plugin requires `usernameField` -- is it passport?).  Can you provide more details of your setup (other Bookshelf plugins used, what your `admin_user` migration looks like, etc) so I can help investigate further?  Or, better yet, could you write a failing test to prove the issue?

I wrote a quick test for your case that seems to pass with this plugin (below).  

```javascript
describe('PasswordMismatchError Issue #4', () => {
  it('authenticates correctly', async () => {
    const knex = new Knex({ client: 'pg' })
    mockKnex.mock(knex)

    const bookshelf = new Bookshelf(knex)
    bookshelf.plugin('registry')
    bookshelf.plugin(securePassword)

    const AdminUser = bookshelf.model('AdminUser', {
      tableName: 'admin_users',
      hasSecurePassword: true,
      hasTimestamps: ['createdAt', 'updatedAt'],
    })

    let user = AdminUser.forge({
      id: 1,
      first_name: 'admin',
      last_name: 'admin',
      email: 'admin@test.com',
      password: 'password',
    })

    user = await user.save();

    await user.authenticate('password');
  })
})
```

**Comment by venables** [comment]
Hi @jmeyers91 - I'm going to take your silence as a sign that you got it working 🎉 .  If that's not the case, please feel free to re-open this issue and I'll hop in to help debug some more.

**Comment by davbeck** [comment]
I was having this same issue. I think I've tracked it down to (camelcase)[https://www.npmjs.com/package/bookshelf-camelcase] plugin.

**Comment by evan-duncan** [comment]
Yeah @davbeck that appears correct. Looking through the code it will call [this.get](https://github.com/venables/bookshelf-secure-password/blob/master/lib/secure-password.js#L138) on the model with a value that's not camelcase which might be the problem? Seems like the other plugin should allow you to call `get` with a snake and came case form and get the same result. I haven't done a ton of investigation on this though. One way to work around this while keeping the `bookshelf-case-converter-plugin` enabled as well as `bookshelf-secure-password` enabled is to set the `hasSecurePassword` value to `"passwordDigest"` instead of using `true`.

```js
const bookshelf = require('../data/bookshelf');

const User = bookshelf.model('User', {
  tableName: 'users',
  hasSecurePassword: 'passwordDigest',
  hasTimestamps: true,
  organization() {
    this.belongsTo('Organization');
  }
});

module.exports = User;
```
